databricks_connection_profile = "your-live-databricks-connection-profile"
dlt_pipeline_storage_path = "s3://<bucket-name>/<your-live-dlt-pipeline-storage-path"
dlt_databricks_database = "your-live-databricks-database"
cluster_instance_type = "i3.xlarge"
cluster_instance_profile_arn = "arn:aws:iam::<accountNumber>:instance-profile/InstanceProfileName"
cluster_cost_center = "cost-center-tag"
cluster_environment_type = "live"
cluster_service = "service-tag"
s3_bucket_name = "<datalake-bucket-name>" # E.g. "husqvarna-datalake-<team>-<env>" or other
